[package]
name = "tdp-tl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
argh = "0.1.9"
indexmap = "1.9.2"
nalgebra = "0.31.4"
nom-gcode = "0.1.1"
